'use strict';
const { v4: uuid } = require("uuid");

/** @type {import('sequelize-cli').Migration} */
module.exports = {
  async up (queryInterface, Sequelize) {
      await queryInterface.bulkInsert("Products", [
        {
          id: uuid(),
          kodebarang: "1",
          namabarang: "Sofa L Besar",
          image: "https://i.ibb.co/61hb8CP/1.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 10 pcs dan 1 buah meja",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "2",
          namabarang: "Sofa L Minimalis",
          image: "https://i.ibb.co/zRnYs5x/2.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 4 pcs", 
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2100000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "3",
          namabarang: "Sofa L",
          image: "https://i.ibb.co/qmg85K4/3.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 3 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "4",
          namabarang: "Sofa L",
          image: "https://i.ibb.co/j6fDB1V/4.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "5",
          namabarang: "Sofa L Besar",
          image: "https://i.ibb.co/FgjbbPG/5.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 10pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "6",
          namabarang: "Sofa Retro L",
          image: "https://i.ibb.co/Cwhxq32/6.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kain Kagawa                                  Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 1800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "7",
          namabarang: "Sofa Retro L putus",
          image: "https://i.ibb.co/KL0DY1p/7.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur dan kain spon                                  Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 1800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "8",
          namabarang: "Sofa Retro L putus ",
          image: "https://i.ibb.co/6Rx69Pq/8.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur dan Kain Mulan/Galaxi                                Bonus Bantal 5pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 1800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "9",
          namabarang: "Sofa Retro L putus",
          image: "https://i.ibb.co/6Rx69Pq/8.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur dan Kain Kagawa                                 Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2400000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "10",
          namabarang: "Sofa L ",
          image: "https://i.ibb.co/GpWp76W/10.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur dan Kain Foxi                                  Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2500000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "11",
          namabarang: "Sofa Retro",
          image: "https://i.ibb.co/61xk8Vw/11.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Kagawa                                 Bonus bantal 3 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 1800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "12",
          namabarang: "Sofa Retro",
          image: "https://i.ibb.co/ccMSpZb/12.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Kagawa                                 Bonus Bantal 4 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2600000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "13",
          namabarang: "Sofa Retro ",
          image: "https://i.ibb.co/bsHXVdX/13.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 4 pcs,",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "14",
          namabarang: "Sofa Retro",
          image: "https://i.ibb.co/hcSMTgC/14.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal Besar Dan Kecil",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2500000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "15",
          namabarang: "Sofa Retro L Putus",
          image: "https://i.ibb.co/bzVrpTJ/15.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Sahrini                                  Bonus Bantal 6 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 4700000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "16",
          namabarang: "Sofa Retro L",
          image: "https://i.ibb.co/TPm43s7/16.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Medili                                  Bonus Bantal 3 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "17",
          namabarang: "Sofa Retro L",
          image: "https://i.ibb.co/XbvSyJM/17.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Foxi                                  Bonus Bantal 3 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "18",
          namabarang: "Sofa Retro",
          image: "https://i.ibb.co/2S5CRrh/18.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu Akasia Bayur dan Kain Bludru Foxi                                  Bonus Bantal 4 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2800000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
        {
          id: uuid(),
          kodebarang: "19",
          namabarang: "Sofa L",
          image: "https://i.ibb.co/1fNRp2N/19.png",
          image2: "",
          image3: "",
          typebarang: "Sofa",
          deskripsibarang: "Semua barang Pre Order (maksimal 7 hari)                                                                                     Bahan: Kayu akasia bayur                                  Bonus Bantal 5 pcs",
          stockbarang: 10,
          satuanbarang: "pcs",
          price: 2000000,
          createdAt: new Date(),
          updatedAt: new Date(),
        },
      ]);
    },
  
    async down(queryInterface, Sequelize) {
      await queryInterface.bulkDelete("Products", null, {});
    },
  };
  
